import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile} from 'node:fs/promises';import {resolve,join} from 'node:path';import {createHash} from 'node:crypto';
import {Queue} from './queue.mjs';import {atomicJson,artifactPath} from './artifacts.mjs';import {processDeliveryOne,deliveryGate} from './delivery.mjs';import {APPROVED_SCOPE} from './policy.mjs';import {fingerprint} from '../publishing/core.mjs';
const hash='a'.repeat(64),sha='b'.repeat(40),pushedSha='c'.repeat(40);
async function fixture(){await mkdir('work/delivery-fixture-tests',{recursive:true});const runtime=await mkdtemp(resolve('work/delivery-fixture-tests/case-')),q=new Queue(join(runtime,'q.db')),now=Date.now(),policy={mode:'POLICY_APPROVED_AUTO',scope:APPROVED_SCOPE,enabled:true,human_authorized:true,expires_at:new Date(now+86400000).toISOString(),min_interval_ms:86400000,max_pending:1},security={unattended_enabled:true,maintenance_verified:true,basis:'ESU_ACTIVE',expires_at:policy.expires_at},snapshot={main_sha:sha,retrieved_at:new Date(now).toISOString(),active_runs:[],pending_sources:[],uncertain_sources:[],publication_holds:[],public_backlog:'CLEAR',last_published_at:0,shared_mutex_verified:true,runner_ready:true};
const id=q.enqueue({task_type:'NEW',topic:'바나나'}).job.job_id;let job=q.claim('fixture');for(const state of ['RESEARCHING','EVIDENCE_READY','DRAFTING','VALIDATING'])job=q.transition(id,job,state);
const source={id:'nh-'+id,title:'가상 시험',category:'음식',tags:['시험'],bodyHtml:'<p>가상 시험 본문</p>',status:'draft',approved:false},draftDigest=await atomicJson(artifactPath(runtime,id,'draft.json'),{source}),review={content_text:'일반 식재료 선택 소개',structural_validation:'PASS',fact_review:'PASS',editorial_review:'PASS',visual_review:'PASS',intent_review:'PASS',source_current:'PASS',draft_fingerprint:draftDigest},validationDigest=await atomicJson(artifactPath(runtime,id,'validation.json'),review);
job=q.transition(id,job,'AWAITING_APPROVAL',{metadata:{base_main_sha:sha,rule_digest:hash,model_digest:hash,evidence_digest:hash,draft_fingerprint:draftDigest,validation_digest:validationDigest}});job=q.release(id,job);
const approval={kind:'POLICY',job_id:id,policy_digest:createHash('sha256').update(JSON.stringify(policy)).digest('hex')},ref='approval-'+createHash('sha256').update(JSON.stringify(approval)).digest('hex')+'.json';await atomicJson(artifactPath(runtime,id,ref),approval);q.authorizePolicy(id,job.state_version,review,policy,ref,{snapshot});
const expected={images:3,h2:4,h3:0,tables:0,highlights:2,faq:2},m={overflowPx:0,wideImages:0,images:3,missingAlt:0,brokenImages:0,nonNativeImages:0,h2:4,h3:0,badHeadingStyles:0,tables:0,badTableWraps:0,highlights:2,highlightColors:2,hiddenHighlights:0,faqQ:2,faqA:2,heroPriority:true,badLazyImages:0},audit={status:'PASS',mode:'ANONYMOUS_READ_ONLY',url:'https://nhunnhun.tistory.com/123',post_fingerprint:fingerprint(source),verified_at:new Date().toISOString(),expected,desktop:{...m,viewport:1440,representativeSourceMatch:true,ogNative:true,categoryVerified:true,tagsVerified:true,allImageSourcesMatch:true},mobile:{...m,viewport:390}};
let pushes=0;const run={id:123,path:'.github/workflows/publish-posts.yml',head_sha:pushedSha,head_branch:'main',event:'push',run_attempt:1,status:'completed',conclusion:'success',created_at:new Date(now-1000).toISOString()},ledger={phase:'published',sourceCommit:pushedSha,fingerprint:fingerprint(source),url:audit.url,editorialTemplateVersion:'R3'},services={snapshot:async()=>snapshot,writer:{prepare:async()=>({job_id:id,path:'posts/nh-'+id+'.json',base_sha:sha}),push:async()=>{pushes++;return {source_sha:pushedSha,workflow_path:run.path};}},checks:async()=>({regression:'PASS',source_validation:'PASS',public_backlog:'CLEAR'}),observe:async()=>({runs:[run],ledger}),audit:async()=>audit,wait:async()=>{}};
return {q,id,runtime,services,configuration:{policy,security},get pushes(){return pushes;}};}
test('disabled policy and unverified maintenance never invoke delivery capabilities',async()=>{assert.equal(deliveryGate({enabled:false},null).allowed,false);const f=await fixture();try{const result=await processDeliveryOne(f.q,f.runtime,f.services,{configuration:{policy:f.configuration.policy,security:{maintenance_verified:false}}});assert.equal(result.state,'DELIVERY_DISABLED');assert.equal(f.pushes,0);assert.equal(f.q.get(f.id).state,'READY_TO_INTEGRATE');}finally{f.q.close()}});
test('canonical mocked workflow plus fresh bound anonymous proof completes exactly once',async()=>{const f=await fixture();try{assert.equal((await processDeliveryOne(f.q,f.runtime,f.services,{configuration:f.configuration})).state,'DONE');assert.equal(f.pushes,1);assert.equal(await processDeliveryOne(f.q,f.runtime,f.services,{configuration:f.configuration}),null);assert.equal(f.pushes,1);assert.ok(f.q.get(f.id).metadata.public_proof_digest);}finally{f.q.close()}});
test('uncertain push or failed workflow blocks reconciliation and never replays',async()=>{for(const failure of ['push','workflow']){const f=await fixture();try{if(failure==='push')f.services.writer.push=async()=>{throw new Error('BLOCKED_RECONCILIATION')};else f.services.observe=async()=>({runs:[{id:123,path:'.github/workflows/publish-posts.yml',head_sha:pushedSha,head_branch:'main',event:'push',run_attempt:1,status:'completed',conclusion:'failure'}]});assert.equal((await processDeliveryOne(f.q,f.runtime,f.services,{configuration:f.configuration})).state,'BLOCKED_RECONCILIATION');assert.equal(await processDeliveryOne(f.q,f.runtime,f.services,{configuration:f.configuration}),null);}finally{f.q.close()}}});
test('one pixel of public mobile overflow cannot become DONE',async()=>{const f=await fixture();try{const original=f.services.audit;f.services.audit=async()=>{const a=await original();return {...a,mobile:{...a.mobile,overflowPx:1}}};assert.equal((await processDeliveryOne(f.q,f.runtime,f.services,{configuration:f.configuration})).state,'BLOCKED_RECONCILIATION');assert.equal(f.q.get(f.id).first_fail_stage,'PUBLIC_VERIFY');}finally{f.q.close()}});
