import test from 'node:test';import assert from 'node:assert/strict';import {parseFruitRow,commonsFiles,fileCandidate} from './discovery.mjs';import {publicReader} from './research.mjs';
const html='<table><tr>'+Array.from({length:19},(_,n)=>'<th>'+({0:'Fruits Serving Size',1:'Calories',11:'Dietary Fiber (g)'}[n]??'Other')+'</th>').join('')+'</tr><tr><td>Pear 1 medium (166 g/5.9 oz)</td>'+Array.from({length:18},(_,n)=>'<td>'+({0:'100',10:'6'}[n]??'0')+'</td>').join('')+'</tr></table>';
test('structured FDA parser preserves portion and exact calorie/fiber columns',()=>{const r=parseFruitRow(html,'Pear');assert.deepEqual([r.grams,r.calories,r.fiber],['166','100','6']);assert.throws(()=>parseFruitRow(html.replace('Dietary Fiber','Other Nutrient'),'Pear'),/E_FDA_COLUMNS/);assert.throws(()=>parseFruitRow(html.replace('166 g','166 kg'),'Pear'),/E_FDA_PORTION/);assert.throws(()=>parseFruitRow(html.replace('Dietary Fiber (g)','Dietary Fiber (%DV)'),'Pear'),/E_FDA_COLUMNS/);assert.throws(()=>parseFruitRow(html.replace('Calories','Calories from Fat'),'Pear'),/E_FDA_COLUMNS/);});
test('Commons candidates never inherit metadata footer CC0 or mark themselves reviewed',()=>{const prefix='<div class="fullImageLink"><a href="https://upload.wikimedia.org/example.jpg"></a></div><td id="fileinfotpl_aut">Author</td><td>Example Person</td><h2 id="Licensing">';assert.equal(fileCandidate(prefix+'Unknown<h2 id="File_history">Footer https://creativecommons.org/publicdomain/zero/1.0/','https://commons.wikimedia.org/wiki/File:Example.jpg'),null);const c=fileCandidate(prefix+'https://creativecommons.org/licenses/by/4.0/<h2 id="File_history">','https://commons.wikimedia.org/wiki/File:Example.jpg');assert.equal(c.license,'CC-BY-4.0');assert.equal(c.visualChecked,false);assert.equal(c.rights_reviewed,false);});
test('category discovery accepts bounded File links only',()=>assert.deepEqual(commonsFiles('<a href="/wiki/File:One.jpg"><a href="/wiki/File:One.jpg"><a href="https://evil.test/test.png"><a href="/wiki/File:Script.svg">'),['https://commons.wikimedia.org/wiki/File:One.jpg']));
test('redirect destination robots is checked before destination content request',async()=>{const calls=[];const read=async url=>{calls.push(url);if(url.endsWith('robots.txt'))return {status:200,url,bytes:Buffer.from('User-agent: *\nDisallow: /blocked'),headers:{}};return {status:302,url,bytes:Buffer.alloc(0),headers:{location:'/blocked'}};};await assert.rejects(publicReader({read})('https://www.fda.gov/food'),/E_RESEARCH_ROBOTS/);assert.equal(calls.includes('https://www.fda.gov/blocked'),false);});

 test('FDA Western pear scope is explicit and ambiguous Korean pear is not mapped',async()=>{const {FOOD_CATALOG}=await import('./discovery.mjs');assert.equal(FOOD_CATALOG['서양배'].row,'Pear');assert.equal(FOOD_CATALOG['배'],undefined);});

 test('produce handling claims require every reviewed original passage',async()=>{const {cleaningClaims}=await import('./discovery.mjs');assert.throws(()=>cleaningClaims('Gently rub produce while holding under plain running water.'),/BLOCKED_EVIDENCE/);});
test('only observed primary Commons preview may replace a huge original',()=>{const html='<div class="fullImageLink"><a href="https://upload.wikimedia.org/original.jpg"><img src="//upload.wikimedia.org/thumb/preview.jpg"></a></div><td>Author</td><td>Person</td><h2 id="Licensing">https://creativecommons.org/licenses/by/4.0/<h2 id="File_history">';const c=fileCandidate(html,'https://commons.wikimedia.org/wiki/File:Example.jpg');assert.equal(c.https_asset_url,'https://upload.wikimedia.org/thumb/preview.jpg');assert.equal(c.original_asset_url,'https://upload.wikimedia.org/original.jpg');assert.equal(c.visualChecked,false);});
