import test from 'node:test';
import assert from 'node:assert/strict';
import {assembleDraft,checkModelDraft} from './draft.mjs';
const evidence={sources:[{url:'https://www.fda.gov/food/a',institution:'FDA',title:'A',published_at:'UNDATED',retrieved_at:'2026-10-04T00:00:00Z',claims:[{id:'c-a',text:'가상 시험 재료 질량 242 g, 열량 130 kcal, 식이섬유 5 g.'}]},{url:'https://www.fda.gov/food/b',institution:'FDA',title:'B',published_at:'UNDATED',retrieved_at:'2026-10-04T00:00:00Z',claims:[{id:'c-b',text:'가상 재료는 흐르는 물로 씻는다.'}]}],images:[0,1,2].map(n=>({https_asset_url:`https://upload.wikimedia.org/test-${n}.jpg`,alt:'가상 시험 이미지 '+n,author:'시험',license:'PUBLIC_DOMAIN',license_url:'https://commons.wikimedia.org/license',original_page_url:'https://commons.wikimedia.org/test-'+n})),internal_links:[{url:'https://nhunnhun.tistory.com/111',title:'관련 재료 세척',relevance_reviewed:true,relevance_reason:'같은 식재료 세척 절차 비교'}],medical_review:'PENDING'};
const model={title:'가상 재료 시험',lead:'가상 시험 자료를 정리합니다.',sections:[{heading:'기준량',text:'기준량은 242 g입니다.',claim_ids:['c-a']},{heading:'열량',text:'열량은 130 kcal입니다.',claim_ids:['c-a']},{heading:'식이섬유',text:'식이섬유는 5 g입니다.',claim_ids:['c-a']},{heading:'세척',text:'흐르는 물로 씻습니다.',claim_ids:['c-b']}],faq:[{question:'기준량?',answer:'242 g입니다.'},{question:'씻는 방법?',answer:'흐르는 물을 사용합니다.'}],summary:['기준량 확인','영양표 확인','세척 방법 확인']};
test('NEW draft passes original source and R3 without self approval',()=>{const d=assembleDraft({job_id:'12345678-1234-1234-1234-123456789012',task_type:'NEW',topic:'시험'},evidence,model);assert.equal(d.source.approved,false);assert.equal(d.source.status,'draft');assert.equal((d.source.bodyHtml.match(/<img /g)||[]).length,3);assert.match(d.renderedHtml,/font-size:26px/);});
test('UPDATE local schema bridge never persists ready or approval',()=>{const d=assembleDraft({job_id:'12345678-1234-1234-1234-123456789012',task_type:'UPDATE',article_id:'356',target_url:'https://nhunnhun.tistory.com/356',expected_title:'원제목'},evidence,model);assert.equal(d.source.approved,false);assert.equal(d.source.targetUrl,'https://nhunnhun.tistory.com/356');});
test('invented evidence ID and numeric claim are rejected',()=>{for(const change of [{claim_ids:['c-invented']},{text:'기준량은 999 g입니다.'}]){const bad=structuredClone(model);Object.assign(bad.sections[0],change);assert.throws(()=>checkModelDraft(bad,evidence));}});
test('model cannot supply approval or raw HTML properties',()=>assert.throws(()=>checkModelDraft({...model,approved:true},evidence),/E_MODEL_SCHEMA/));
test('apostrophes in real author attribution preserve safe valid HTML',()=>{const e=structuredClone(evidence);e.images[0].author="Photographer's name";const result=assembleDraft({job_id:'12345678-1234-1234-1234-123456789012',task_type:'NEW',topic:'시험'},e,model);assert.ok(result.source.bodyHtml.includes("Photographer's name"));assert.equal(result.source.approved,false);});
test('precut refrigeration cannot be generalized to all whole fruit',()=>{const e=structuredClone(evidence);e.sources[1].claims.push({id:'c-cut',text:'이미 자른 농산물은 냉장하거나 얼음 위에 둔다.'});const bad=structuredClone(model);bad.summary[0]='모든 과일은 냉장한다.';assert.throws(()=>checkModelDraft(bad,e),/E_MODEL_CONDITION_OMITTED/);bad.summary[0]='이미 자른 농산물은 냉장한다.';assert.doesNotThrow(()=>checkModelDraft(bad,e));});

test('ACTIVE source blocks absent related links, self links and unreviewed relevance',()=>{for(const links of [[],[{url:'https://nhunnhun.tistory.com/111',title:'관련',relevance_reviewed:false}]]){const e=structuredClone(evidence);e.internal_links=links;assert.throws(()=>assembleDraft({job_id:'12345678-1234-1234-1234-123456789012',task_type:'NEW',topic:'시험'},e,model),/E_ACTIVE_RELATED/);}const e=structuredClone(evidence);assert.throws(()=>assembleDraft({job_id:'12345678-1234-1234-1234-123456789012',task_type:'UPDATE',article_id:'111',target_url:'https://nhunnhun.tistory.com/111',expected_title:'원제목'},e,model),/E_ACTIVE_SELF_LINK/);});

test('nutrient serving basis cannot be presented as a condition of hygiene and storage',()=>{assert.throws(()=>checkModelDraft({...model,lead:'FDA 기준량 126g의 바나나에 적용되는 보관 절차입니다.'},evidence),/E_MODEL_BASIS_SCOPE/);});
