import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync,readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join,resolve,dirname,basename } from 'node:path';
import { Queue } from './queue.mjs';
import { processOne } from './orchestrator.mjs';
import { artifactPath } from './artifacts.mjs';
async function fixture(fn){const root=resolve(tmpdir()),dir=mkdtempSync(join(root,'nh-orch-'));try{await fn(dir);}finally{if(dirname(resolve(dir))!==root||!basename(dir).startsWith('nh-orch-'))throw new Error('E_TEST_CLEANUP_PATH');rmSync(dir,{recursive:true,force:true});}}
const request={task_type:'NEW',topic:'시험'};
test('successful stages persist evidence, draft and validation without approval',()=>fixture(async dir=>{const q=new Queue(join(dir,'q.db'));const id=q.enqueue(request).job.job_id;await processOne(q,dir,{research:async()=>({sources:['fixture']}),draft:async()=>({body:'fixture'}),validate:async()=>({status:'PASS'})});assert.equal(q.get(id).state,'AWAITING_APPROVAL');assert.equal(q.get(id).lease_owner,null);assert.match(q.get(id).metadata.evidence_digest,/^[a-f0-9]{64}$/);assert.match(q.get(id).metadata.draft_fingerprint,/^[a-f0-9]{64}$/);for(const name of ['evidence.json','draft.json','validation.json'])assert.ok(JSON.parse(readFileSync(artifactPath(dir,id,name),'utf8')));q.close();}));
test('missing evidence blocks the affected work and permits the next independent work',()=>fixture(async dir=>{const q=new Queue(join(dir,'q.db'));const a=q.enqueue(request).job.job_id;const b=q.enqueue({...request,topic:'다른 시험'}).job.job_id;await processOne(q,dir,{research:async()=>{throw new Error('BLOCKED_EVIDENCE');}});assert.equal(q.get(a).state,'BLOCKED_EVIDENCE');assert.equal(q.claim('next').job_id,b);q.close();}));
test('stop checkpoints before generation and never requests public mutation',()=>fixture(async dir=>{const q=new Queue(join(dir,'q.db'));const id=q.enqueue(request).job.job_id;const controller=new AbortController();let drafted=false;await processOne(q,dir,{research:async()=>{controller.abort();return {};},draft:async()=>{drafted=true;}},{signal:controller.signal});assert.equal(drafted,false);assert.equal(q.get(id).state,'RETRY_WAIT');assert.equal(q.get(id).last_error_code,'E_STOP_REQUESTED');q.close();}));
test('retry budget survives resumes and does not loop forever',()=>fixture(async dir=>{const q=new Queue(join(dir,'q.db'));const id=q.enqueue(request).job.job_id;for(let n=0;n<4;n++){if(n)q.resume(id);await processOne(q,dir,{research:async()=>{throw new Error('E_FIXTURE_READ');}});}assert.equal(q.get(id).last_error_code,'E_ATTEMPT_BUDGET');assert.equal(q.get(id).attempts_by_stage.RESEARCHING,3);q.close();}));
test('semantic review hold is not labeled awaiting publication approval',()=>fixture(async dir=>{const q=new Queue(join(dir,'q.db'));const id=q.enqueue(request).job.job_id;await processOne(q,dir,{research:async()=>({}),draft:async()=>({}),validate:async()=>({fact_review:'HOLD',editorial_review:'PASS'})});assert.equal(q.get(id).state,'BLOCKED_EVIDENCE');assert.equal(q.get(id).first_fail_stage,'VALIDATING');q.close();}));
test('verified review checkpoint keeps prior artifacts and stage retry budget',()=>fixture(async dir=>{const q=new Queue(join(dir,'q.db'));const id=q.enqueue(request).job.job_id;await processOne(q,dir,{research:async()=>({}),draft:async()=>({}),validate:async()=>{throw new Error('E_REVIEW_INCOMPLETE');}});const old=q.get(id);q.resumeValidation(id,old.state_version,{rule_digest:'a'.repeat(64),base_main_sha:'b'.repeat(40),draft_fingerprint:old.metadata.draft_fingerprint});let research=0,drafting=0;await processOne(q,dir,{research:async()=>{research++;},draft:async()=>{drafting++;},validate:async()=>({fact_review:'PASS',editorial_review:'PASS'})});assert.equal(research,0);assert.equal(drafting,0);assert.equal(q.get(id).state,'AWAITING_APPROVAL');assert.equal(q.get(id).attempts_by_stage.VALIDATING,2);q.close();}));
test('semantic hold cannot resume as an infrastructure-only review',()=>fixture(async dir=>{const q=new Queue(join(dir,'q.db'));const id=q.enqueue(request).job.job_id;await processOne(q,dir,{research:async()=>({}),draft:async()=>({}),validate:async()=>({fact_review:'HOLD'})});const job=q.get(id);assert.throws(()=>q.resumeValidation(id,job.state_version,{rule_digest:'a'.repeat(64),base_main_sha:'b'.repeat(40),draft_fingerprint:job.metadata.draft_fingerprint}),/E_CHECKPOINT_STATE/);q.close();}));
