import test from 'node:test';import assert from 'node:assert/strict';import {proveNativeAltRecovery} from '../publishing/alt-native-recovery-proof.mjs';import {draftImageGridAltSource,parseImageGridMacros,applyMappedImageGridAlt} from '../publishing/alt-image-grid-contract.mjs';import {maintenanceHash} from '../publishing/alt-maintenance-contract.mjs';
const metadata={title:'title',category:'food',tags:['food'],representativeImage:'same',visibility:'20'};
const ref=n=>'kage@asset'+n+'/folder/version/photo.png?credential=old&amp;expires=123&amp;allow_ip=&amp;allow_referer=&amp;signature=old';
const plain=n=>'[##_Image|'+ref(n)+'|CDM|1.3|{"originWidth":100,"originHeight":80,"width":100,"height":80,"style":"alignCenter","filename":"fixture.png"}_##]';
const attrs='data-is-animation="false" data-origin-width="100" data-origin-height="80" data-filename="grid.png" style="width:50%;" data-widthpercent="50"';
function fixture(){const originalHtml='<p>unchanged</p>'+plain(1)+'[##_ImageGrid|'+ref(2)+','+ref(3)+'|'+attrs+','+attrs+'|caption_##]';const publicSources=[1,2,3].map(n=>'https://blog.kakaocdn.net/dn/asset'+n+'/folder/version/photo.png');const request=draftImageGridAltSource(originalHtml,metadata,{articleId:'334',imageIndex:1,newAlt:'intended alt'},publicSources,'repair-grid-proof').maintenance;const mapping={version:'macro-asset-map-v1',assetSha256s:parseImageGridMacros(originalHtml).map(x=>maintenanceHash(x.asset))};const expected=applyMappedImageGridAlt(originalHtml,metadata,request,mapping).targetHtml;const actualNativeHtml=expected.replace(/"(originWidth|originHeight|width|height)":(\d+)/g,'"$1":"$2"').replaceAll('&amp;','&').replaceAll('credential=old','credential=new').replaceAll('signature=old','signature=new');return {originalHtml,metadata,request,mapping,actualNativeHtml};}
test('dedicated reconstruction proves only observed numeric and signing serializations without ledger mutation',()=>{const proof=proveNativeAltRecovery(fixture());assert.equal(proof.images,3);assert.equal(proof.numericStringConversions,4);assert.equal(proof.signedReferenceSerializations,3);assert.equal(proof.publicationEnabled,false);assert.equal(proof.ledgerMutation,false);assert.match(proof.providerBodyPreservation,/UNKNOWN/);});
test('wrong alt, nonmacro text, style, asset, order, dimensions and unsigned query changes reject',()=>{const f=fixture();const variations=[f.actualNativeHtml.replace('intended alt','wrong alt'),f.actualNativeHtml.replace('unchanged','changed'),f.actualNativeHtml.replace('alignCenter','alignLeft'),f.actualNativeHtml.replace('asset1/','asset9/'),f.actualNativeHtml.replace('asset2/','assetTEMP/').replace('asset3/','asset2/').replace('assetTEMP/','asset3/'),f.actualNativeHtml.replace('"originWidth":"100"','"originWidth":"101"'),f.actualNativeHtml.replace('credential=new','unapproved=new')];for(const actualNativeHtml of variations)assert.throws(()=>proveNativeAltRecovery({...f,actualNativeHtml}));});

test('caption numeric-looking literals, duplicate metadata keys and signed reference controls cannot be normalized',()=>{
 const f=fixture();const originalHtml=f.originalHtml.replace('"filename":"fixture.png"','"filename":"fixture.png","caption":'+JSON.stringify('"originWidth":100'));
 const src=draftImageGridAltSource(originalHtml,metadata,{articleId:'334',imageIndex:1,newAlt:'intended alt'},[1,2,3].map(n=>'https://blog.kakaocdn.net/dn/asset'+n+'/folder/version/photo.png'),'repair-grid-caption');
 const mapping={version:'macro-asset-map-v1',assetSha256s:parseImageGridMacros(originalHtml).map(x=>maintenanceHash(x.asset))};
 const intended=applyMappedImageGridAlt(originalHtml,metadata,src.maintenance,mapping).targetHtml;
 const altered=intended.replace(JSON.stringify('"originWidth":100'),JSON.stringify('"originWidth":"100"'));
 assert.throws(()=>proveNativeAltRecovery({originalHtml,metadata,request:src.maintenance,mapping,actualNativeHtml:altered}));
 for(const actualNativeHtml of [f.actualNativeHtml.replace('credential=new','credential=new#fragment'),f.actualNativeHtml.replace('credential=new','credential=new\n'),f.actualNativeHtml.replace('"originWidth":"100"','"originWidth":"100","originWidth":"100"')])assert.throws(()=>proveNativeAltRecovery({...f,actualNativeHtml}));
});
