import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { evaluateContent, assertContentStandard, contentDigest } from '../publishing/content-standards.mjs';
import { targetsFromChanged, changedSourcePaths, reviewScaffold } from '../publishing/validate-content.mjs';
import { fixture, refresh } from './fixtures/content-r1/factory.mjs';
const evaluate = pair => evaluateContent(pair.source,pair.manifest,{today:'2026-10-07'});
const has=(pair,code)=>assert.ok(evaluate(pair).errors.some(e=>e.code===code),JSON.stringify(evaluate(pair)));
for(const domain of ['food','nutrient','medicine','disease']) test(`domain contract: ${domain}`,()=>{const p=fixture(domain);assert.equal(evaluate(p).passed,true,JSON.stringify(evaluate(p).errors));});
test('PASS explicitly does not claim autonomous medical verification',()=>assert.equal(evaluate(fixture()).semanticVerification,'editor-attested-not-automatically-proven'));
test('source without R1 cannot mutate',()=>assert.throws(()=>assertContentStandard({...fixture().source,contentStandard:undefined}),/E_CONTENT_STANDARD_REQUIRED/));
test('category and domain mismatch is blocked',()=>{const p=fixture();p.source.category='약학';refresh(p);has(p,'E_CONTENT_CATEGORY_MISMATCH');});
test('unresolved classification cannot pass',()=>{const p=fixture();p.manifest.classification.status='unresolved';has(p,'E_CONTENT_CLASSIFICATION');});
test('watermelon cannot use medicine rules',()=>{const p=fixture('medicine');p.manifest.classification.topic='수박';has(p,'E_CONTENT_CLASSIFICATION_CONFLICT');});
test('eating pear retains original words and normalized fruit meaning',()=>{const p=fixture('food',{entityId:'food:pear',topic:'배'});p.manifest.classification.rawInput='먹는 배 글을 적어줘';assert.equal(evaluate(p).passed,true,JSON.stringify(evaluate(p).errors));assert.equal(p.manifest.classification.rawInput,'먹는 배 글을 적어줘');});
test('pear without disambiguation is blocked',()=>{const p=fixture('food',{entityId:'food:pear',topic:'배'});p.manifest.classification.meaning='모호한 단어';has(p,'E_CONTENT_AMBIGUOUS_TOPIC');});
test('apple profile requires regional and cultivar decisions',()=>{const p=fixture('food',{entityId:'food:apple',topic:'사과'});p.manifest.extensions.origins.applies=false;has(p,'E_CONTENT_TOPIC_EXTENSION');});
test('vitamin C profile cannot silently omit product comparison',()=>{const p=fixture('nutrient',{entityId:'nutrient:vitamin-c',topic:'비타민C'});assert.equal(evaluate(p).passed,true,JSON.stringify(evaluate(p).errors));p.manifest.extensions.products.applies=false;has(p,'E_CONTENT_TOPIC_EXTENSION');});
test('changing entity ID does not evade known-topic requirements',()=>{const p=fixture('food',{entityId:'food:apple',topic:'사과'});p.manifest.classification.entityId='food:other';has(p,'E_CONTENT_ENTITY_CANONICAL');});
for(const field of ['title','bodyHtml','category','representativeImageUrl']) test(`review is invalidated by changed ${field}`,()=>{const p=fixture();p.source[field]+=' 변경';has(p,'E_CONTENT_REVIEW_STALE');});
test('review is invalidated by approval changes',()=>{const p=fixture();p.source.approved=false;has(p,'E_CONTENT_REVIEW_STALE');});
test('digest canonicalizes key ordering without ignoring content',()=>{const s=fixture().source;assert.equal(contentDigest(s),contentDigest(Object.fromEntries(Object.entries(s).reverse())));});
test('extension decision cannot be omitted',()=>{const p=fixture();delete p.manifest.extensions.longTerm;has(p,'E_CONTENT_EXTENSION_DECISION');});
test('not-applicable needs a meaningful reason',()=>{const p=fixture();p.manifest.extensions.origins.reason='해당 없음';has(p,'E_CONTENT_EXTENSION_DECISION');});
test('declared long-term topic needs actual timeline and follow-up answers',()=>{const p=fixture('nutrient');p.manifest.extensions.longTerm.applies=true;has(p,'E_CONTENT_REQUIRED_MODULE');});
test('heading without an answer fails',()=>{const p=fixture();p.manifest.coverage[0].answerQuote='존재하지 않는 실제 효과와 복용방법에 대한 문장';has(p,'E_CONTENT_ANSWER_NOT_FOUND');});
test('answer in an unrelated heading cannot satisfy coverage',()=>{const p=fixture();p.manifest.coverage[0].heading=p.manifest.coverage[1].heading;has(p,'E_CONTENT_ANSWER_NOT_FOUND');});
test('health evidence does not count image/product links',()=>{const p=fixture();p.manifest.sources.forEach(s=>s.role='product');has(p,'E_CONTENT_HEALTH_EVIDENCE');});
test('orphan source references fail',()=>{const p=fixture();p.manifest.coverage[0].sourceIds=['no-such-source'];has(p,'E_CONTENT_MODULE_CITATION');});
test('footer-only source is insufficient for a claimed section citation',()=>{const p=fixture();p.manifest.coverage[0].sourceIds=['ref-b'];has(p,'E_CONTENT_MODULE_CITATION');});
test('future checking dates fail',()=>{const p=fixture();p.manifest.sources[0].checkedAt='2027-01-01';has(p,'E_CONTENT_SOURCE_SCHEMA');});
test('invalid calendar dates fail',()=>{const p=fixture();p.manifest.sources[0].checkedAt='2026-02-30';has(p,'E_CONTENT_SOURCE_SCHEMA');});
test('credentials in source links fail',()=>{const p=fixture();p.manifest.sources[0].url='https://user:secret@example.org/reference';has(p,'E_CONTENT_SOURCE_URL');});
test('domestic medicines require MFDS authorization source',()=>{const p=fixture('medicine');p.manifest.sources[0].role='health';has(p,'E_CONTENT_KR_AUTHORIZATION');});
test('all three other domains must be considered, not forcibly included',()=>{const p=fixture();assert.equal(evaluate(p).passed,true);delete p.manifest.connections.medicine;has(p,'E_CONTENT_CONNECTION');});
test('included connection requires a real answer in the section',()=>{const p=fixture();p.manifest.connections.nutrient={status:'included',reason:'실제 관련 영양소를 연결하는 설명이 필요합니다.',heading:p.manifest.coverage[0].heading,answerQuote:'본문에 존재하지 않는 답변이므로 통과하면 안 됩니다.',relationship:'nutrient-source',sourceIds:['ref-a']};has(p,'E_CONTENT_CONNECTION_BODY');});
test('unknown combination relationship is blocked',()=>{const p=fixture('nutrient',{enabled:['combinations']});p.manifest.combinations[0].relationship='synergy-assumed';has(p,'E_CONTENT_COMBINATION_TYPE');});
test('compatible-only is distinct from extra benefit',()=>{const p=fixture('nutrient',{enabled:['combinations']});assert.equal(evaluate(p).passed,true,JSON.stringify(evaluate(p).errors));assert.equal(p.manifest.combinations[0].relationship,'compatible-only');});
test('comparison without a common basis fails',()=>{const p=fixture('food',{enabled:['comparison']});p.manifest.comparisons[0].basis='';has(p,'E_CONTENT_COMPARISON_BASIS');});
test('product selection must say how to check the criterion',()=>{const p=fixture('nutrient',{enabled:['products']});p.manifest.selectionCriteria[0].howToCheck='';has(p,'E_CONTENT_SELECTION_CRITERION');});
test('editor-only criticism is blocked',()=>{const p=fixture();p.source.bodyHtml+='<p>기존 표현은 삭제하는 것이 맞습니다.</p>';refresh(p);has(p,'E_CONTENT_EDITOR_MEMO');});
test('urgent safety instructions are not penalized as negative tone',()=>{const p=fixture();p.source.bodyHtml=p.source.bodyHtml.replace('<h2>핵심 정리','<p>호흡이 어려우면 즉시 진료가 필요합니다. 임의로 약을 중단하지 마세요.</p><h2>핵심 정리');refresh(p);assert.equal(evaluate(p).passed,true,JSON.stringify(evaluate(p).errors));});
test('technical terms need nearby plain-language explanations',()=>{const p=fixture();p.source.bodyHtml=p.source.bodyHtml.replace('<h2>핵심 정리','<p>생체이용률을 확인합니다.</p><h2>핵심 정리');refresh(p);has(p,'E_CONTENT_TERM_UNEXPLAINED');});
test('nearby glossary explanation passes',()=>{const p=fixture();p.source.bodyHtml=p.source.bodyHtml.replace('<h2>핵심 정리','<p>생체이용률은 섭취한 성분이 몸에서 이용될 수 있는 정도를 뜻합니다.</p><h2>핵심 정리');p.manifest.glossary=[{term:'생체이용률',explanation:'섭취한 성분이 몸에서 이용될 수 있는 정도'}];refresh(p);assert.equal(evaluate(p).passed,true,JSON.stringify(evaluate(p).errors));});
test('pending editorial review cannot pass',()=>{const p=fixture();p.manifest.review.status='pending';has(p,'E_CONTENT_REVIEW_REQUIRED');});
test('review checklist requires an explanation, not only true/pass',()=>{const p=fixture();p.manifest.review.checks.accuracy.note='';has(p,'E_CONTENT_REVIEW_CHECK');});
test('scaffold never fabricates approval or resolved classification',()=>{const p=fixture();const s=reviewScaffold(p.source);assert.equal(s.review.status,'pending');assert.equal(s.classification.status,'unresolved');assert.equal(s.sources.length,0);assert.equal(evaluateContent(p.source,s).passed,false);});
test('missing sidecar fails before browser use',()=>{const p=fixture();const dir=mkdtempSync(join(tmpdir(),'content-missing-'));try{assert.throws(()=>assertContentStandard(p.source,{root:dir}),/E_CONTENT_REVIEW_MISSING/);}finally{rmSync(dir,{recursive:true,force:true});}});
test('sidecar path cannot escape its namespace',()=>assert.throws(()=>assertContentStandard({...fixture().source,id:'../x'}),/E_CONTENT_REVIEW_PATH/));
test('new posts and existing updates use separate review namespaces',()=>{const p=fixture();const dir=mkdtempSync(join(tmpdir(),'content-review-'));try{mkdirSync(join(dir,'content-reviews','posts'),{recursive:true});writeFileSync(join(dir,'content-reviews','posts',p.source.id+'.json'),JSON.stringify(p.manifest));assert.equal(assertContentStandard(p.source,{root:dir,today:'2026-10-07'}).passed,true);assert.throws(()=>assertContentStandard({...p.source,articleId:'343'},{root:dir}),/E_CONTENT_REVIEW_MISSING/);}finally{rmSync(dir,{recursive:true,force:true});}});
test('review-only change targets its source but does not publish by itself',()=>assert.deepEqual(targetsFromChanged(['content-reviews/updates/test-pear.json','docs/x.md']),['updates/test-pear.json']));
test('unsafe git range values are rejected without shell interpolation',()=>assert.throws(()=>changedSourcePaths('main;echo x','a'.repeat(40)),/E_CONTENT_GIT_RANGE/));
test('manufacturer or local promotion cannot substitute for primary health evidence',()=>{const p=fixture();p.manifest.sources.forEach(s=>s.kind='manufacturer');has(p,'E_CONTENT_HEALTH_EVIDENCE');});
test('disease red flags require a visibly labeled safety block containing the answer',()=>{const p=fixture('disease');p.source.bodyHtml=p.source.bodyHtml.replace(' data-kind="danger"','');refresh(p);has(p,'E_CONTENT_SAFETY_EMPHASIS');});
test('medicine contraindications require a visibly labeled safety block',()=>{const p=fixture('medicine');p.source.bodyHtml=p.source.bodyHtml.replace(' data-kind="caution"','');refresh(p);has(p,'E_CONTENT_SAFETY_EMPHASIS');});
test('malformed benefit evidence is rejected with diagnostics instead of crashing',()=>{const p=fixture('nutrient',{enabled:['combinations']});p.manifest.combinations[0].relationship='benefit';p.manifest.combinations[0].sourceIds='ref-a';assert.doesNotThrow(()=>evaluate(p));has(p,'E_CONTENT_COMBINATION_EVIDENCE');});
test('non-array warning resolutions cannot crash the reviewer',()=>{const p=fixture();p.source.bodyHtml=p.source.bodyHtml.replace('<h2>',`<p>${'긴 문장입니다. '.repeat(80)}</p><h2>`);refresh(p);p.manifest.review.warningResolutions='invalid';assert.doesNotThrow(()=>evaluate(p));has(p,'E_CONTENT_REVIEW_SCHEMA');});
test('comparison subjects must be distinct text labels',()=>{const p=fixture('nutrient',{enabled:['comparison']});p.manifest.comparisons[0].left={not:'a label'};has(p,'E_CONTENT_COMPARISON_BASIS');});


test('active content validation enforces scan density but archival audit may skip it',()=>{
  const p=fixture();
  p.source.bodyHtml=p.source.bodyHtml.replace('<h2>핵심 정리</h2>','<h2>추가 설명</h2><p>'+ '가'.repeat(320) +'</p><h2>핵심 정리</h2>');
  refresh(p);
  has(p,'E_CONTENT_SCAN_EMPHASIS');
  const archival=evaluateContent(p.source,p.manifest,{today:'2026-10-07',enforceScanDensity:false});
  assert.equal(archival.passed,true,JSON.stringify(archival.errors));
  assert.equal(archival.scanDensityPolicy,'archival-skip');
});
