import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {inspectNativePreflight,assertNativePreflightEnvironment} from '../publishing/native-text-preflight.mjs';
import {maintenanceHash as hash} from '../publishing/alt-maintenance-contract.mjs';
import {nativeImages,nativePlainText,nativeTextSlots} from '../publishing/native-text-contract.mjs';
const html='<h2>Old</h2><p>Wrong</p>[##_Image|kage@a/b/c/img.png|CDM|1.3|{"caption":"Picture","alt":"Existing"}_##]';
const metadata={title:'Old',category:'음식',tags:['x'],representativeImage:'credential=synthetic-private',visibility:'20'};
function fixture(){const slot=nativeTextSlots(html).find(x=>x.raw==='Wrong');const maintenance={operation:'native-text-surgical-v1',articleId:'200',expectedTitle:'Old',targetTitle:'New',expectedBodySha256:hash(html),expectedMetadataSha256:hash(JSON.stringify(metadata)),expectedPublicTextSha256:hash(nativePlainText(html)),targetPublicTextSha256:hash(nativePlainText(html.replace('Wrong','Correct'))),patches:[{start:slot.start,length:slot.length,expectedTextSha256:hash('Wrong'),newText:'Correct'}],cleanupPatches:[],captionPatches:[]};return {source:{id:'repair-native-test',articleId:'200',targetUrl:'https://nhunnhun.tistory.com/200',expectedCurrentTitle:'Old',title:'New',status:'draft',approved:false,operation:maintenance.operation,maintenance},observed:{originalHtml:html,metadata},captureBaseline:async()=>({assetMapping:{version:'native-text-assets-v1',assetSha256s:nativeImages(html).map(x=>hash(x.asset))}})};}
test('read-only preflight proves draft conditions without approving, staging or leaking originals',async()=>{const f=fixture();const before=JSON.stringify(f.source);const r=await inspectNativePreflight(f.source,f.observed,f);assert.equal(r.status,'PASS');assert.equal(r.finalSubmitCount,0);assert.equal(r.editorInputCount,0);assert.equal(JSON.stringify(f.source),before);assert.equal(Object.values(r.checks).every(x=>x==='PASS'),true);for(const sensitive of ['credential','synthetic-private','originalHtml','metadataSha256','kage@'])assert.equal(JSON.stringify(r).includes(sensitive),false);});
for(const [name,change,expected]of [
 ['mode serialization drift',f=>f.observed.originalHtml+=' ','E_TEXT_BODY_DRIFT'],
 ['metadata drift',f=>f.observed.metadata={...metadata,tags:['other']},'E_TEXT_METADATA_DRIFT'],
 ['non-draft source',f=>f.source.approved=true,'E_NATIVE_PREFLIGHT_DRAFT_SCOPE'],
 ['scope escape',f=>f.source.articleId='264','E_NATIVE_PREFLIGHT_DRAFT_SCOPE'],
 ['public baseline mismatch',f=>f.captureBaseline=async()=>{throw Error('E_TEXT_PUBLIC_MAPPING');},'E_TEXT_PUBLIC_MAPPING']
])test(name,async()=>{const f=fixture();change(f);const r=await inspectNativePreflight(f.source,f.observed,f);assert.equal(r.status,'FAIL');assert.equal(r.code,expected);assert.equal(r.finalSubmitCount,0);});
test('unexpected error text is redacted',async()=>{const f=fixture();f.captureBaseline=async()=>{throw Error('credential=synthetic-private');};const r=await inspectNativePreflight(f.source,f.observed,f);assert.equal(r.code,'E_NATIVE_PREFLIGHT_OBSERVATION');assert.equal(JSON.stringify(r).includes('credential'),false);});
test('workflow environment refuses mutation or non-main scope',()=>{const e={ALT_SNAPSHOT_READ_ONLY:'true',ALT_OBSERVATION_SCOPE:'native-identity3',GITHUB_ACTIONS:'true',GITHUB_REF:'refs/heads/main',UPDATE_ENABLED:'false',GITHUB_RUN_ID:'123',RUNNER_TEMP:'fixture'};assertNativePreflightEnvironment(e);for(const delta of [{UPDATE_ENABLED:'true'},{GITHUB_REF:'refs/heads/other'},{ALT_OBSERVATION_SCOPE:'other'},{GITHUB_ACTIONS:'false'},{RUNNER_TEMP:''}])assert.throws(()=>assertNativePreflightEnvironment({...e,...delta}),/READ_ONLY_GATE/);});
test('preflight uses existing read-only observer, draft path and no editor input API',()=>{const code=readFileSync(new URL('../publishing/native-text-preflight.mjs',import.meta.url),'utf8');assert.match(code,/observeAltEditor\(page/);assert.match(code,/docs\/candidates/);assert.doesNotMatch(code,/\.fill\(|insertText\(|keyboard\.press|submit\.click/);const workflow=readFileSync(new URL('../.github/workflows/observe-alt-maintenance.yml',import.meta.url),'utf8');assert.match(workflow,/contents: read/);assert.match(workflow,/scope == 'native-identity3'/);assert.match(workflow,/safe-results\.json/);assert.doesNotMatch(workflow,/\.raw\.private/);});
