import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {updateFingerprint} from '../publishing/update-core.mjs';
import {joinPublishedReview} from './evidence-dates-join-published-review.mjs';
// Portable synthetic fixtures; never treated as production publication evidence.
const source={id:'evidence-dates-381-season-fix-20261010',articleId:'381',targetUrl:'https://nhunnhun.tistory.com/381',title:'synthetic',bodyHtml:'<p>synthetic</p>'};
const bytes=Buffer.from(JSON.stringify(source));
const row={articleId:'381',publicUrl:source.targetUrl,currentSourceId:'chestnut-calories-benefits-storage-20261006',currentWholeSourceCheckedAt:null,currentWholeNextReviewAt:null,preparedSourceId:source.id,preparedFile:'updates/'+source.id+'.json',preparedDigest:crypto.createHash('sha256').update(bytes).digest('hex'),preparedWholeStatus:'PASS_ON_PREPARED_SOURCE_PENDING_PUBLIC_UPDATE',remainingSourceClaimGaps:[],sourceReviewPerformedAt:'2026-10-10',preparedNextReviewAt:'2026-11-09'};
const register={rows:[{sourceId:row.currentSourceId,sourceFile:'posts/chestnut-calories-benefits-storage-20261006.json',publicUrl:row.publicUrl,sourceCheckedAt:null},{sourceId:'direct-yuja-cheong-20261009',publicUrl:'https://nhunnhun.tistory.com/398',sourceCheckedAt:null},{sourceId:'unreviewed',publicUrl:'https://nhunnhun.tistory.com/405',sourceCheckedAt:null}]};
const prior={mappings:[{oldSourceId:'direct-yuja-cheong-20261009',publicUrl:'https://nhunnhun.tistory.com/398',activeFileSha256:'existing398',historicalSourceCheckedAt:null}]};
const fp=updateFingerprint(source);
const ledger={phase:'updated',articleId:'381',url:row.publicUrl,fingerprint:fp,sourceCommit:'synthetic-sha',runUrl:'https://example.invalid/run',publicResult:{status:'PUBLIC_VERIFIED',sourceId:source.id,url:row.publicUrl,fingerprint:fp,sourceCommit:'synthetic-sha',checkedAt:'2026-10-10T10:00:00Z',runUrl:'https://example.invalid/run'}};
const before=JSON.stringify(register),beforePrior=JSON.stringify(prior);
const joined=joinPublishedReview(register,prior,row,bytes,ledger);
assert.equal(joined.remainingActionableOriginalRecords,1);assert.equal(joined.supersededOriginalRecords,2);
assert.equal(JSON.stringify(register),before);assert.equal(JSON.stringify(prior),beforePrior);
assert.deepEqual(joined.mappings[0],prior.mappings[0]);
assert.deepEqual(joinPublishedReview(register,joined,row,bytes,ledger),joined);
assert.throws(()=>joinPublishedReview(register,prior,row,Buffer.concat([bytes,Buffer.from(' ')]),ledger),/E_CURRENT_SOURCE_DRIFT/);
for(const phase of ['submitting','failed','prepared'])assert.throws(()=>joinPublishedReview(register,prior,row,bytes,{...ledger,phase}),/E_PUBLIC_UPDATE_UNCONFIRMED/);
const bad=(change,pattern)=>{const l=structuredClone(ledger);change(l);assert.throws(()=>joinPublishedReview(register,prior,row,bytes,l),pattern);};
bad(l=>l.publicResult.status='PUBLIC_VERIFICATION_MISMATCH',/E_PUBLIC_UPDATE_UNCONFIRMED/);
bad(l=>l.publicResult.sourceId='other',/E_LEDGER_TARGET/);
bad(l=>l.url='https://nhunnhun.tistory.com/405',/E_LEDGER_TARGET/);
bad(l=>l.publicResult.fingerprint='wrong',/E_LEDGER_FINGERPRINT/);
bad(l=>l.publicResult.sourceCommit='wrong',/E_LEDGER_EVIDENCE/);
bad(l=>delete l.publicResult.checkedAt,/E_LEDGER_EVIDENCE/);
assert.throws(()=>joinPublishedReview(register,prior,{...row,remainingSourceClaimGaps:['unread']},bytes,ledger),/E_REVIEW_INCOMPLETE/);
assert.throws(()=>joinPublishedReview(register,prior,{...row,preparedWholeStatus:'UNKNOWN'},bytes,ledger),/E_REVIEW_INCOMPLETE/);
const wrong=structuredClone(register);wrong.rows[0].sourceCheckedAt='2020-01-01';
assert.throws(()=>joinPublishedReview(wrong,prior,row,bytes,ledger),/E_HISTORICAL_JOIN/);
console.log('PASS portable fixtures: published exact join; immutable history/prior398; idempotency; source drift, prepared/failed/submitting, mismatch, target, fingerprint, commit, missing evidence and incomplete review rejected');
