// Generated from the user-approved varied preview. Source text is never rewritten.
const BASE_CSS=".nh-direct-v2 *{box-sizing:border-box}.nh-direct-v2 .article-body{margin:0;background:#fff;color:#263541;font-family:Arial,'Malgun Gothic',sans-serif;font-size:16px;line-height:1.85}.nh-direct-v2 .article-body{max-width:820px;margin:auto;padding:48px 24px 90px}.nh-direct-v2 header{border-bottom:1px solid #e8eaed;padding:14px 24px;color:#927656;font-size:13px}.nh-direct-v2 h1{font-size:32px;line-height:1.4;letter-spacing:-1px;margin:12px 0 26px}.nh-direct-v2 h2{display:flex;align-items:center;gap:14px;font-size:24px;line-height:1.45;margin:56px 0 22px;letter-spacing:-.6px}.nh-direct-v2 h2 small{font-size:23px;font-weight:800;color:#a95325;min-width:36px;line-height:1.45;border-bottom:3px solid #df9567;padding:2px 0}.nh-direct-v2 h3{font-size:18px;line-height:1.5;margin:0 0 8px;color:#24343e}.nh-direct-v2 p{margin:12px 0 20px}.nh-direct-v2 img{width:100%;height:270px;object-fit:contain;display:block;margin:24px 0 40px}.nh-direct-v2 strong{font-weight:700}.nh-direct-v2 mark{background:#fff0b9;padding:0 2px}.nh-direct-v2 u{text-decoration-color:#ba6338;text-underline-offset:4px}.nh-direct-v2 .table-scroll{overflow:auto;border:1px solid #e1e6e8;border-radius:10px}.nh-direct-v2 table{width:100%;border-collapse:collapse;font-size:14px;min-width:480px}.nh-direct-v2 th{background:#f3f5f4;text-align:left;color:#54625c}.nh-direct-v2 td,.nh-direct-v2 th{padding:12px 15px;border-bottom:1px solid #e6eae8}.nh-direct-v2 tr:last-child td{border:0}.nh-direct-v2 .effects article{display:flex;gap:18px;padding:22px 0;border-bottom:1px solid #e4e8e6}.nh-direct-v2 .badge{flex-shrink:0;font-size:13px;color:#a96b46;font-weight:bold;padding-top:3px}.nh-direct-v2 .effects article p,.nh-direct-v2 .pairs article p,.nh-direct-v2 .cautions article p,.nh-direct-v2 .storage article p{margin:0}.nh-direct-v2 .pairs{background:#f6f7f4;padding:8px 26px;border-radius:12px}.nh-direct-v2 .pairs article{display:flex;gap:18px;padding:24px 0;border-bottom:1px solid #dde2d9}.nh-direct-v2 .pairs article:last-child{border:0}.nh-direct-v2 .pairs h3{color:#4c634e}.nh-direct-v2 .cautions article{padding:18px 22px;margin:12px 0;border-left:3px solid #d39a5b;background:#fffaf1;display:flex;gap:16px}.nh-direct-v2 .cautions article:nth-child(2){background:#fff1e8;border-color:#c97849}.nh-direct-v2 .storage article{display:flex;gap:16px;padding:18px 0}.nh-direct-v2 .storage .badge{color:#4d7960;font-size:20px}.nh-direct-v2 .note{color:#8d7865;font-size:13px}@media(max-width:600px){.nh-direct-v2 .article-body{padding:24px 20px 50px}.nh-direct-v2 h1{font-size:26px}.nh-direct-v2 h2{font-size:21px;margin-top:40px}.nh-direct-v2 .article-body{font-size:16px}.nh-direct-v2 .pairs{padding:6px 17px}.nh-direct-v2 .cautions article{padding:17px 15px}.nh-direct-v2 img{height:210px}}";
const LINK_CSS="/* Body links are recognisable independently of bold emphasis. */\n.nh-direct-v2 .article-body a[href] {color:#176b82!important;text-decoration:underline!important;text-decoration-color:#65aabc!important;text-decoration-thickness:2px!important;text-underline-offset:4px;background:#eef8fa;border-radius:3px;box-decoration-break:clone;-webkit-box-decoration-break:clone;transition:background-color .15s,color .15s;}\n.nh-direct-v2 .article-body a[href]:hover {color:#114d62!important;background:#d9eff4;text-decoration-color:currentColor!important;}\n.nh-direct-v2 .article-body a[href]:focus-visible {outline:2px solid #176b82;outline-offset:3px;}\n.nh-direct-v2 .article-body a[href] strong {color:inherit!important;}\n";
const CSS=BASE_CSS+LINK_CSS+"/* Item number badges: distinct from the large section heading numbers. */\n.nh-direct-v2 :is(.effects,.pairs,.cautions,.storage) > article {\n  display:grid!important;grid-template-columns:32px minmax(0,1fr);column-gap:12px!important;row-gap:10px;align-items:center;\n}\n.nh-direct-v2 :is(.effects,.pairs,.cautions,.storage) > article > .badge {\n  grid-column:1;grid-row:1;display:inline-flex!important;align-items:center;justify-content:center;\n  width:32px;height:32px;padding:0!important;border-radius:9px;background:#fff0e1;color:#a54b1c!important;\n  font-size:14px!important;font-weight:800!important;line-height:1;box-shadow:inset 0 0 0 1px #f4d5b8;\n}\n.nh-direct-v2 :is(.effects,.pairs,.cautions,.storage) > article > div {display:contents!important;}\n.nh-direct-v2 :is(.effects,.pairs,.cautions,.storage) > article h3 {grid-column:2;grid-row:1;margin:0!important;font-size:19px;line-height:1.5;}\n.nh-direct-v2 :is(.effects,.pairs,.cautions,.storage) > article p {grid-column:1 / -1;margin:0!important;}\n\n.nh-direct-v2 .storage > article > .badge {background:#eaf3eb;color:#3e6b49!important;box-shadow:inset 0 0 0 1px #cddfcf;font-size:18px!important;} \n";
const EFFECTS_CSS='.nh-direct-v2 .effects{background:#f7f9fc;border:1px solid #dce4ec;border-radius:12px;padding:4px 24px;margin:22px 0}.nh-direct-v2 .effects article:last-child{border-bottom:0}@media(max-width:600px){.nh-direct-v2 .effects{padding:4px 16px}}';
export function renderDirectArticle(html){
 let n=0;
 let body=html.replace(/<h2>([\s\S]*?)<\/h2>/g,(_,title)=>{n++;return '<h2 id="direct-section-'+n+'"><small>'+String(n).padStart(2,'0')+'</small>'+title.replace(/^\d+[.)]\s*/,'')+'</h2>';});
 let section=0;
 body=body.split(/(?=<h2 id=)/).map(chunk=>{
  if(chunk.startsWith('<h2'))section++;
  const kind=({3:'effects',4:'pairs',5:'cautions',6:'storage'})[section];
  if(!kind)return chunk;
  return chunk.replace(/<(?:ul|ol)>([\s\S]*?)<\/(?:ul|ol)>/g,(_,inside)=>{let i=0;return '<div class="'+kind+'">'+inside.replace(/<li><strong>([\s\S]*?)<\/strong>([\s\S]*?)<\/li>/g,(_,label,text)=>'<article><span class="badge">'+(kind==='storage'?'✓':String(++i).padStart(2,'0'))+'</span><div><h3>'+label.replace(/[:：]\s*$/,'')+'</h3><p>'+text+'</p></div></article>')+'</div>';});
 }).join('');
 body=body.replace(/<table>/g,'<div class="table-scroll"><table>').replace(/<\/table>/g,'</table></div>');
 return '<style>'+CSS+EFFECTS_CSS+'</style><div class="nh-direct-v2"><div class="article-body">'+body+'</div></div>';
}
